kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes  1;
    events {
      worker_connections  1024;
    }
    http {
      include       mime.types;
      default_type  application/octet-stream;
      log_format    main_post   '$remote_addr - [$time_local] '
                                '$host "$request" $status $bytes_sent [$request_body] '
                                '"$http_referer" "$http_user_agent" '
                                '"$gzip_ratio" $upstream_response_time';
      sendfile      on;
      keepalive_timeout 65;

      server {
        listen       80;
        server_name  localhost;
        root         /var/www/softgrader;
        client_max_body_size 32m;
        error_page 404 = /index.php;

        location / {
          try_files $uri @router;
        }
        location @router {
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_param SCRIPT_FILENAME $document_root/index.php;
          include fastcgi_params;
        }
        location = /favicon.ico {
          log_not_found off;
          access_log off;
        }
        location = /robots.txt {
          allow all;
          log_not_found off;
          access_log off;
        }
        location ~* ^/application/.+.(css|js)$ {
          expires -1;
          add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        }
        location ~* ^.+.(jpg|jpeg|gif|png|ico|css|js)$ {
          access_log off;
          expires    30d;
        }
        location ~ /\.ht {
          deny  all;
          access_log off;
          log_not_found off;
        }
      }
    }