apiVersion: v1
kind: Service
metadata:
  name: softgrader-service
  labels:
    app: softgrader-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: softgrader
  externalIPs:
    - 99.99.99.99
