name: Linter

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Linter
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSS: true
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_PHP_BUILTIN: true
          VALIDATE_PHP_PHPCS: true
          VALIDATE_PHP_PHPSTAN: true
          VALIDATE_GITHUB_ACTIONS: true
          FILTER_REGEX_EXCLUDE: .*./tests.*
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MULTI_STATUS: false